### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by rockywind** [Brummi/BehindTheScenes#1]
Hello. Thank you for sharing this amazing project!

May I know when the code will be released?

I am looking forward to running this project!

**Comment by Brummi** [comment]
hi!
thank you for your interest in our project!
we are working to release the code at some point this week.
best,
felix

**Comment by rockywind** [comment]
Thank you very much!

**Comment by Brummi** [comment]
Code has been (mostly) released. Some parts will follow in the coming days / weeks as we finish our camera ready version for the conference.
