### ISSUE TITLE
Question about of generate novel view animations

### ISSUE THREAD

**Issue by jelleopard** [Brummi/BehindTheScenes#16]
When I know the R and T of the current view, how do I generate the motion trajectory of the new view on the kitti dataset to generate the demo, can you provide the code?
How to get this file of "./scripts/videos/trajectories/simple_movement.npy"?

**Comment by Brummi** [comment]
Hi!
Sorry for the late reply!

I generate these camera trajectories with blender. You can use this example script within blender to export a trajectory:

[scripts/blender/export_camera_trj.py](https://github.com/Brummi/BehindTheScenes/blob/main/scripts/blender/export_camera_trj.py)

Best,
Felix
