### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: 'scripts/videos/trajectories/simple_movement.npy'"

### ISSUE THREAD

**Issue by rockywind** [Brummi/BehindTheScenes#2]
Hi, @Brummi 
Can you show me the example code for how to generate the camera trajectories?
So I can set the camera trajectories on our own dataset?

**Comment by Brummi** [comment]
Hi!
sorry, this was my bad.
These files were ignored due to the gitignore in the  initial commit. I added them now.
Best,
Felix

**Comment by rockywind** [comment]
Hi,
how can I generate the simple_movement.npy in our own dataset?
Can you give me some example code?
Thanks for advance!

Best
Xaioquan

**Comment by Brummi** [comment]
I generate the camera trajectory by first animating a camera in blender and then exporting the camera trajectory.
Blender offers a Python API and built-in script editor.
I used the script provided [scripts/blender/export_camera_trj.py](https://github.com/Brummi/BehindTheScenes/blob/main/scripts/blender/export_camera_trj.py) script. If you run this within blender, it will generate a compatible npy trajectory file for the specified camera.

In general, this npy file contains n 4x4 camera to world transformation matrices (one for every frame).

**Comment by rockywind** [comment]
Thanks , I have a try!
