### ISSUE TITLE
Missing some files in KITTI-RAW Poses in datasets/kitti_raw/orb-slam_poses.

### ISSUE THREAD

**Issue by liguopeng0923** [Brummi/BehindTheScenes#20]
<img width="666" alt="image" src="https://github.com/Brummi/BehindTheScenes/assets/61257834/b9101413-cc84-4f5d-ad5a-e11a5e2f8684">

**Comment by Brummi** [comment]
There must be something wrong with the paths in your configs.
These files are present in the repository: 

[datasets/kitti_raw/orb-slam_poses](https://github.com/Brummi/BehindTheScenes/tree/main/datasets/kitti_raw/orb-slam_poses)

Best,
Felix

**Comment by liguopeng0923** [comment]
These files are not in the link mentioned by you.

As show, the 0928 director only has [two files ](https://github.com/Brummi/BehindTheScenes/assets/61257834/a7544d87-16d2-492d-bf87-2510d351aa96).

Others are missing!

**Comment by Brummi** [comment]
The categories campus and person of the KITTI Raw dataset are generally not used for training depth networks, as they are mostly stationary. 
The sequences you mentioned are from these categories (they are also not part of the training of other methods like Monodepth2).

**Comment by rockywind** [comment]
Can you show me some tutorial to how to use orbslam to generate the pose?
