### ISSUE TITLE
These files are not in the link mentioned by you.

### ISSUE THREAD

**Issue by liguopeng0923** [Brummi/BehindTheScenes#22]
These files are not in the link mentioned by you.

As shown, the 0928 director only has [two files ](https://github.com/Brummi/BehindTheScenes/assets/61257834/a7544d87-16d2-492d-bf87-2510d351aa96).

Others are missing!

_Originally posted by @liguopeng0923 in https://github.com/Brummi/BehindTheScenes/issues/20#issuecomment-1620306010_

**Comment by Brummi** [comment]
See #20
