### ISSUE TITLE
Experiment  settings of other works mentioned in the paper

### ISSUE THREAD

**Issue by zsz-pro** [Brummi/BehindTheScenes#25]
Thanks for your great work! I wonder what's the experiment settings of these 3 works, mono? stereo? or with fisheye? 
![image](https://github.com/Brummi/BehindTheScenes/assets/61933660/efc5814a-5d5a-4f6a-b110-8a4ea716a509)

**Comment by Brummi** [comment]
Hi!
Monodepth2 and MINE use pretrained checkpoints, where training used stereo.
We retrained PixelNeRF with the same setting as our full model with fisheye.
Best,
Felix

**Comment by zsz-pro** [comment]
Wow！Thanks for your quick reply！It's really helpful!
