### ISSUE TITLE
Some details I feel confused about

### ISSUE THREAD

**Issue by zsz-pro** [Brummi/BehindTheScenes#26]
Nice work! There are some details I feel confused about, like the code below. Why do you define two evaluators? They are exactly similar except for the time when they are called. There might be some engineering strategies at play, and I would appreciate the opportunity to learn from them.

    # We define two evaluators as they wont have exactly similar roles:
    # - `evaluator` will save the best model based on validation score
    evaluator = create_evaluator(model, metrics=eval_metrics, criterion=criterion if loss_during_validation else None, config=config)

    if vis_loader is not None:
        visualizer = create_evaluator(model, metrics=eval_metrics, criterion=criterion if loss_during_validation else None, config=config)
    else:
        visualizer = None

**Comment by supremeccccc** [comment]
the main difference is that they use different dataloader, the evaluator uses a test set( length 256) and concerns about the metric while we mainly use visualizer to. plot images whose dataset length is one.

**Comment by Brummi** [comment]
the previous answer by @supremeccccc is correct.

**Comment by zsz-pro** [comment]
OK，thanks！
