### ISSUE TITLE
Train on KITTI-360 with fisheye

### ISSUE THREAD

**Issue by supremeccccc** [Brummi/BehindTheScenes#27]
![image](https://github.com/Brummi/BehindTheScenes/assets/140047983/8942663f-b3e4-43e7-8aae-f3ea97877080)
![image](https://github.com/Brummi/BehindTheScenes/assets/140047983/b89a72a9-51ea-4003-baaa-d775bb25d9af)
![image](https://github.com/Brummi/BehindTheScenes/assets/140047983/b4ec9d20-5916-401c-9035-579877fbecdc)
The images are recon depth, recon img, and invailds.
The traning loss did't decrease, if i use fisheye data to train in KITTI360 . I have checked i use the same config as the original one except i didn't preprocess the dataset. It seems that the invalid regions are large.
Could you give me some advice for proper training?

**Comment by Brummi** [comment]
To me, the images look good for early stages of the training. The training takes quite long and the loss only goes down slowly.
For how many iterations did you train?
The preprocessing only speeds up dataloading and does not have an effect on the losses.

**Comment by supremeccccc** [comment]
Thanks for your reply. You are right. The previous results were taken in early epochs. I continue training to 20 epochs and the recon depth seems good now.
![image](https://github.com/Brummi/BehindTheScenes/assets/140047983/d8de69d4-884f-477a-a85d-b481fda6c08a)
![image](https://github.com/Brummi/BehindTheScenes/assets/140047983/3d0bc005-3ef1-456f-835b-dfe4241cf6de)
![image](https://github.com/Brummi/BehindTheScenes/assets/140047983/1d2fcbf2-47ea-4e1a-ad06-731be9f4eaf0)

It is surprising that the recon images of the fisheye camera are really bad in most scenes. However, it has a significant influence on occupancy prediction. I was wondering if we could get a better result by simultaneously encoding the fisheye camera images since the invalid area of the sample feature could be eliminated.
