### ISSUE TITLE
details with the keyParam ray_batch_size: 4096

### ISSUE THREAD

**Issue by LamHoCN** [Brummi/BehindTheScenes#28]
hey Brummi~ another amazing job after momoRec ~
i have some question with the ray_batch_size, Is this an experience param？
If I trained bts on a custom dataset, Does this parameter have a big impact？

**Comment by Brummi** [comment]
The ray batch size should not be too small. But if you leave it as is, it should be fine.
If you use a much higher resolution, you should probably also increase the ray_batch_size.

Best,
Felix

**Comment by LamHoCN** [comment]
Hi Felix~
Thanks for your reply. It helps a lot.
Best,
merlin
