### ISSUE TITLE
How to generate the training data?

### ISSUE THREAD

**Issue by rockywind** [Brummi/BehindTheScenes#3]
Hi,
When I launch the training process, I met the error below.
I think the training need a processed data, not the raw data.
````
  File "/rockywin.wang/NeRF/BehindTheScenes/datasets/kitti_360/kitti_360_dataset.py", line 571, in __getitem__
    imgs_p_left, imgs_f_left, imgs_p_right, imgs_f_right = self.load_images(sequence, img_ids, load_left, load_right, img_ids_fish=img_ids_fish)
  File "/rockywin.wang/NeRF/BehindTheScenes/datasets/kitti_360/kitti_360_dataset.py", line 442, in load_images
    img_perspective = cv2.cvtColor(cv2.imread(os.path.join(self.data_path, "data_2d_raw", seq, "image_00", self._perspective_folder, f"{id:010d}.png")), cv2.COLOR_BGR2RGB).astype(np.float32) / 255
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-afu9cjzs/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
````

**Comment by Brummi** [comment]
Sorry about the inconvenience.

Explanation:
I "preprocessed" files by resizing them to a lower resolution and then saving them. This made training much faster, as the dataset had to load smaller files (especially for the fisheye cameras). You can do the same with the preprocess_kitti_360 script.
However, this is optional and the dataloader can also deal with the raw files.

I just updated the data config to not use the preprocessed images.
(change the configs/data/kitti_360.yaml file)
