### ISSUE TITLE
Why the input data shape is [4, 8, 3,192, 640] when the batch szie is 16?

### ISSUE THREAD

**Issue by rockywind** [Brummi/BehindTheScenes#5]
Hi,
I am confused about the input data shape. Can you help me?
The input data shape is [4, 8, 3,192, 640] when the batch size is 16.
The input data shape is [2, 8, 3,192, 640] when the batch size is 8.
The input data shape is [1, 8, 3,192, 640] when the batch size is 2.
And what's the meaning of the number 8?

**Comment by Brummi** [comment]
Hi,
sure.
Could you please specify where you observe these data shapes?

**Comment by rockywind** [comment]
Hi,
This is the code [reference](https://github.com/Brummi/BehindTheScenes/blob/b866ad031e0a7c81c3a6067c99b6c604aae2c6fa/models/bts/trainer.py#L89).
![image](https://user-images.githubusercontent.com/14838781/226568853-0e4c680a-e0b8-439b-88d2-a64e4cfadca1.png)

**Comment by Brummi** [comment]
Assuming these are the shapes of the images that the network receives from the data loader.
[n, v, c, h, w]
n = Batch size
v = Number of frames / camera views per sample (e.g. for KITTI-360 it's 2 timesteps x 2 cameras (forward, fisheye) x 2 stereo (left, right) = 8)
c =  Number of color channels
h = Height
w = Width

The batch size is directly fed to the dataloader. So it might be that you are running a system with 4 GPUs and the code automatically distributes the batch onto those 4 GPUs.

**Comment by rockywind** [comment]
Thank you very much!
Yes I am running in a system with 4 GPUs

**Comment by ruili3** [comment]
> Thank you very much! Yes I am running in a system with 4 GPUs

Hi may I ask how you make code work on multiple GPUs? Did you follow the advice raised from [here](https://github.com/Brummi/BehindTheScenes/issues/23#issuecomment-1633338426)?

Thank you a lot for the answer!
