### ISSUE TITLE
Can the kitti raw data  be replace with the kitti odometry data set

### ISSUE THREAD

**Issue by rockywind** [Brummi/BehindTheScenes#6]
Hi,
I have a [kitti odometry dataset](https://www.cvlibs.net/datasets/kitti/eval_odometry.php), but I don't have kitti raw data.
Can I run the code of BehindTheScene in kitti odometry data with the config of kitti raw data?
I found the [SceneRF](https://github.com/astra-vision/SceneRF) is training in kitti odometry dataset.

**Comment by Brummi** [comment]
Yes, I think you should be able to do that.
There is also an implementation for a KITTI Odometry loader in the repo, but I haven't used it in a while and it is not "officially" supported. So you might have to double check whether the implementation is still up-to-date.

Also, I made the experience that the GT odometry poses are fairly bad. Therefore, I used the same poses I used in [MonoRec](https://github.com/Brummi/MonoRec).

However, note that KITTI Odometry and KITTI Raw don't have fisheye cameras, which are fairly important for recovering geometry in occluded regions.

**Comment by rockywind** [comment]
Thanks, I have a try!

**Comment by rockywind** [comment]
Hi, 
Can you train the model on [nuscene](https://www.nuscenes.org/nuscenes?externalData=all&mapData=all&modalities=Any) dataset? The nuscene dataset has six cameras surrounding the car.

**Comment by Brummi** [comment]
I am sure it would be possible. I have never tried it myself though.

Similarly to waymo, the FoVs of the cameras are very narrow, which makes it hard to get enough overlap of the camera frustums.
However, you can predict the density field based on multiple input images (the code supports this using the combine_ids list, which allows to consider multiple frames as a single one, but with different intrinsics / extrinsics)

Check out the waymo mode for frame_sample_mode in [trainer.py](https://github.com/Brummi/BehindTheScenes/blob/main/models/bts/trainer.py).

**Comment by rockywind** [comment]
Thank you vety much.
I have a try.
