### ISSUE TITLE
Question about the ground truth occupancy.

### ISSUE THREAD

**Issue by HyunHo99** [Brummi/BehindTheScenes#8]
Thanks for your great work! I have a question about using the ground truth occupancy. Could you please help me with it?
I think that if objects move during a shoot, there is a possibility that the whole object  or parts of it will be carved out.
When you were creating the ground truth occupancy, how did you deal with moving objects?
Thank you!

**Comment by Brummi** [comment]
Hi,
thank you for your interest in our work!
you are right, our current way of obtaining "ground truth" / reference occupancy would not produce ideal results when there are moving objects in the scene.
however, KITTI-360 contains very few moving objects, as it was captured in quiet residential areas. furthermore, we double checked all frames in the test split to not contain moving objects.

futhermore, we initially evaluated occupancy using 3D bounding boxes, which can deal with moving objects. while the lidar evaluation is more precise, the trends (e.g. ours achieving best results) were the same.

hope this helps!
Best,
Felix
